version: "3.4"

# Services definition for local building & deployment

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app-npm}:${IMAGES_TAG:-latest}
    build:
      target: app_npm
    # Deploy
    volumes:
      - ./app/app:/app
