version: '3.4'

# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}:${DOCKER_TAG:-latest}
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        PORT: ${APP_PORT:-80}
    # Deploy
    ports:
      # HTTP
      - target: ${APP_PORT:-80}
        published: ${APP_HTTP_PORT:-80}
        protocol: tcp
